name: Build and run
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update packages
        run: |
          go get -u ./...
          go mod download
          go mod tidy

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build main
        run: go build ./cmd/stats/main.go

      - name: Build Docker image
        run: docker build -t app .

      - name: Running integration test
        run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
